using Entities.Concrete;
using Entities.Concrete.OtherEntities;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Concrete.Seeds
{
    public static class CountrySeed
    {
        public static void CountriesSeed(this ModelBuilder modelBuilder)
        {

            var countries = new List<Country>
            {
                new Country{Id=1, Name="Afghanistan",Row=1,ShortName="AF"},
                new Country{Id=2, Name="Albania",Row=2,ShortName="AL"},
                new Country{Id=3, Name="Algeria",Row=3,ShortName="DZ"},
                new Country{Id=4, Name="American Samoa",Row=4,ShortName="AS"},
                new Country{Id=5, Name="Andorra",Row=5,ShortName="AD"},
                new Country{Id=6, Name="Angola",Row=6,ShortName="AO"},
                new Country{Id=7, Name="Anguilla",Row=7,ShortName="AI"},
                new Country{Id=8, Name="Antarctica",Row=8,ShortName="AQ"},
                new Country{Id=9, Name="Antigua and Barbuda",Row=9,ShortName="AG"},
                new Country{Id=10, Name="Argentina",Row=10,ShortName="AR"},
                new Country{Id=11, Name="Armenia",Row=11,ShortName="AM"},
                new Country{Id=12, Name="Aruba",Row=12,ShortName="AW"},
                new Country{Id=13, Name="Australia",Row=13,ShortName="AU"},
                new Country{Id=14, Name="Austria",Row=14,ShortName="AT"},
                new Country{Id=15, Name="Azerbaijan",Row=15,ShortName="AZ"},
                new Country{Id=16, Name="Bahamas (the)",Row=16,ShortName="BS"},
                new Country{Id=17, Name="Bahrain",Row=17,ShortName="BH"},
                new Country{Id=18, Name="Bangladesh",Row=18,ShortName="BD"},
                new Country{Id=19, Name="Barbados",Row=19,ShortName="BB"},
                new Country{Id=20, Name="Belarus",Row=20,ShortName="BY"},
                new Country{Id=21, Name="Belgium",Row=21,ShortName="BE"},
                new Country{Id=22, Name="Belize",Row=22,ShortName="BZ"},
                new Country{Id=23, Name="Benin",Row=23,ShortName="BJ"},
                new Country{Id=24, Name="Bermuda",Row=24,ShortName="BM"},
                new Country{Id=25, Name="Bhutan",Row=25,ShortName="BT"},
                new Country{Id=26, Name="Bolivia (Plurinational State of)",Row=26,ShortName="BO"},
                new Country{Id=27, Name="Bonaire, Sint Eustatius and Saba",Row=27,ShortName="BQ"},
                new Country{Id=28, Name="Bosnia and Herzegovina",Row=28,ShortName="BA"},
                new Country{Id=29, Name="Botswana",Row=29,ShortName="BW"},
                new Country{Id=30, Name="Bouvet Island",Row=30,ShortName="BV"},
                new Country{Id=31, Name="Brazil",Row=31,ShortName="BR"},
                new Country{Id=32, Name="British Indian Ocean Territory (the)",Row=32,ShortName="IO"},
                new Country{Id=33, Name="Brunei Darussalam",Row=33,ShortName="BN"},
                new Country{Id=34, Name="Bulgaria",Row=34,ShortName="BG"},
                new Country{Id=35, Name="Burkina Faso",Row=35,ShortName="BF"},
                new Country{Id=36, Name="Burundi",Row=36,ShortName="BI"},
                new Country{Id=37, Name="Cabo Verde",Row=37,ShortName="CV"},
                new Country{Id=38, Name="Cambodia",Row=38,ShortName="KH"},
                new Country{Id=39, Name="Cameroon",Row=39,ShortName="CM"},
                new Country{Id=40, Name="Canada",Row=40,ShortName="CA"},
                new Country{Id=41, Name="Cayman Islands (the)",Row=41,ShortName="KY"},
                new Country{Id=42, Name="Central African Republic (the)",Row=42,ShortName="CF"},
                new Country{Id=43, Name="Chad",Row=43,ShortName="TD"},
                new Country{Id=44, Name="Chile",Row=44,ShortName="CL"},
                new Country{Id=45, Name="China",Row=45,ShortName="CN"},
                new Country{Id=46, Name="Christmas Island",Row=46,ShortName="CX"},
                new Country{Id=47, Name="Cocos (Keeling) Islands (the)",Row=47,ShortName="CC"},
                new Country{Id=48, Name="Colombia",Row=48,ShortName="CO"},
                new Country{Id=49, Name="Comoros (the)",Row=49,ShortName="KM"},
                new Country{Id=50, Name="Congo (the Democratic Republic of the)",Row=50,ShortName="CD"},
                new Country{Id=51, Name="Congo (the)",Row=51,ShortName="CG"},
                new Country{Id=52, Name="Cook Islands (the)",Row=52,ShortName="CK"},
                new Country{Id=53, Name="Costa Rica",Row=53,ShortName="CR"},
                new Country{Id=54, Name="Croatia",Row=54,ShortName="HR"},
                new Country{Id=55, Name="Cuba",Row=55,ShortName="CU"},
                new Country{Id=56, Name="Curaçao",Row=56,ShortName="CW"},
                new Country{Id=57, Name="Cyprus",Row=57,ShortName="CY"},
                new Country{Id=58, Name="Czechia",Row=58,ShortName="CZ"},
                new Country{Id=59, Name="Côte dIvoire",Row=59,ShortName="CI"},
                new Country{Id=60, Name="Denmark",Row=60,ShortName="DK"},
                new Country{Id=61, Name="Djibouti",Row=61,ShortName="DJ"},
                new Country{Id=62, Name="Dominica",Row=62,ShortName="DM"},
                new Country{Id=63, Name="Dominican Republic (the)",Row=63,ShortName="DO"},
                new Country{Id=64, Name="Ecuador",Row=64,ShortName="EC"},
                new Country{Id=65, Name="Egypt",Row=65,ShortName="EG"},
                new Country{Id=66, Name="El Salvador",Row=66,ShortName="SV"},
                new Country{Id=67, Name="Equatorial Guinea",Row=67,ShortName="GQ"},
                new Country{Id=68, Name="Eritrea",Row=68,ShortName="ER"},
                new Country{Id=69, Name="Estonia",Row=69,ShortName="EE"},
                new Country{Id=70, Name="Eswatini",Row=70,ShortName="SZ"},
                new Country{Id=71, Name="Ethiopia",Row=71,ShortName="ET"},
                new Country{Id=72, Name="Falkland Islands (the) [Malvinas]",Row=72,ShortName="FK"},
                new Country{Id=73, Name="Faroe Islands (the)",Row=73,ShortName="FO"},
                new Country{Id=74, Name="Fiji",Row=74,ShortName="FJ"},
                new Country{Id=75, Name="Finland",Row=75,ShortName="FI"},
                new Country{Id=76, Name="France",Row=76,ShortName="FR"},
                new Country{Id=77, Name="French Guiana",Row=77,ShortName="GF"},
                new Country{Id=78, Name="French Polynesia",Row=78,ShortName="PF"},
                new Country{Id=79, Name="French Southern Territories (the)",Row=79,ShortName="TF"},
                new Country{Id=80, Name="Gabon",Row=80,ShortName="GA"},
                new Country{Id=81, Name="Gambia (the)",Row=81,ShortName="GM"},
                new Country{Id=82, Name="Georgia",Row=82,ShortName="GE"},
                new Country{Id=83, Name="Germany",Row=83,ShortName="DE"},
                new Country{Id=84, Name="Ghana",Row=84,ShortName="GH"},
                new Country{Id=85, Name="Gibraltar",Row=85,ShortName="GI"},
                new Country{Id=86, Name="Greece",Row=86,ShortName="GR"},
                new Country{Id=87, Name="Greenland",Row=87,ShortName="GL"},
                new Country{Id=88, Name="Grenada",Row=88,ShortName="GD"},
                new Country{Id=89, Name="Guadeloupe",Row=89,ShortName="GP"},
                new Country{Id=90, Name="Guam",Row=90,ShortName="GU"},
                new Country{Id=91, Name="Guatemala",Row=91,ShortName="GT"},
                new Country{Id=92, Name="Guernsey",Row=92,ShortName="GG"},
                new Country{Id=93, Name="Guinea",Row=93,ShortName="GN"},
                new Country{Id=94, Name="Guinea-Bissau",Row=94,ShortName="GW"},
                new Country{Id=95, Name="Guyana",Row=95,ShortName="GY"},
                new Country{Id=96, Name="Haiti",Row=96,ShortName="HT"},
                new Country{Id=97, Name="Heard Island and McDonald Islands",Row=97,ShortName="HM"},
                new Country{Id=98, Name="Holy See (the)",Row=98,ShortName="VA"},
                new Country{Id=99, Name="Honduras",Row=99,ShortName="HN"},
                new Country{Id=100, Name="Hong Kong",Row=100,ShortName="HK"},
                new Country{Id=101, Name="Hungary",Row=101,ShortName="HU"},
                new Country{Id=102, Name="Jamaica",Row=102,ShortName="JM"},
                new Country{Id=103, Name="Japan",Row=103,ShortName="JP"},
                new Country{Id=104, Name="Jersey",Row=104,ShortName="JE"},
                new Country{Id=105, Name="Jordan",Row=105,ShortName="JO"},
                new Country{Id=106, Name="Kazakhstan",Row=106,ShortName="KZ"},
                new Country{Id=107, Name="Kenya",Row=107,ShortName="KE"},
                new Country{Id=108, Name="Kiribati",Row=108,ShortName="KI"},
                new Country{Id=109, Name="Korea (the Democratic Peoples Republic of)",Row=109,ShortName="KP"},
                new Country{Id=110, Name="Korea (the Republic of)", Row = 110, ShortName="KR" },
                new Country{Id=111, Name="Kuwait", Row = 111, ShortName="KW" },
                new Country{Id=112, Name="Kyrgyzstan", Row = 112, ShortName="KG" },
                new Country{Id=113, Name="Lao Peoples Democratic Republic(the)",Row=113,ShortName="LA"},
                new Country{Id=114, Name="Latvia", Row = 114, ShortName="LV" },
                new Country{Id=115, Name="Lebanon", Row = 115, ShortName="LB" },
                new Country{Id=116, Name="Lesotho", Row = 116, ShortName="LS" },
                new Country{Id=117, Name="Liberia", Row = 117, ShortName="LR" },
                new Country{Id=118, Name="Libya", Row = 118, ShortName="LY" },
                new Country{Id=119, Name="Liechtenstein", Row = 119, ShortName="LI" },
                new Country{Id=120, Name="Lithuania", Row = 120, ShortName="LT" },
                new Country{Id=121, Name="Luxembourg", Row = 121, ShortName="LU" },
                new Country{Id=122, Name="Macao", Row = 122, ShortName="MO" },
                new Country{Id=123, Name="Madagascar", Row = 123, ShortName="MG" },
                new Country{Id=124, Name="Malawi", Row = 124, ShortName="MW" },
                new Country{Id=125, Name="Malaysia", Row = 125, ShortName="MY" },
                new Country{Id=126, Name="Maldives", Row = 126, ShortName="MV" },
                new Country{Id=127, Name="Mali", Row = 127, ShortName="ML" },
                new Country{Id=128, Name="Malta", Row = 128, ShortName="MT" },
                new Country{Id=129, Name="Marshall Islands (the)", Row = 129, ShortName="MH" },
                new Country{Id=130, Name="Martinique", Row = 130, ShortName="MQ" },
                new Country{Id=131, Name="Mauritania", Row = 131, ShortName="MR" },
                new Country{Id=132, Name="Mauritius", Row = 132, ShortName="MU" },
                new Country{Id=133, Name="Mayotte", Row = 133, ShortName="YT" },
                new Country{Id=134, Name="Mexico", Row = 134, ShortName="MX" },
                new Country{Id=135, Name="Micronesia (Federated States of)", Row = 135, ShortName="FM" },
                new Country{Id=136, Name="Moldova (the Republic of)", Row = 136, ShortName="MD" },
                new Country{Id=137, Name="Monaco", Row = 137, ShortName="MC" },
                new Country{Id=138, Name="Mongolia", Row = 138, ShortName="MN" },
                new Country{Id=139, Name="Montenegro", Row = 139, ShortName="ME" },
                new Country{Id=140, Name="Montserrat", Row = 140, ShortName="MS" },
                new Country{Id=141, Name="Morocco", Row = 141, ShortName="MA" },
                new Country{Id=142, Name="Mozambique", Row = 142, ShortName="MZ" },
                new Country{Id=143, Name="Myanmar", Row = 143, ShortName="MM" },
                new Country{Id=144, Name="Namibia", Row = 144, ShortName="NA" },
                new Country{Id=145, Name="Nauru", Row = 145, ShortName="NR" },
                new Country{Id=146, Name="Nepal", Row = 146, ShortName="NP" },
                new Country{Id=147, Name="Netherlands (the)", Row = 147, ShortName="NL" },
                new Country{Id=148, Name="New Caledonia", Row = 148, ShortName="NC" },
                new Country{Id=149, Name="New Zealand", Row = 149, ShortName="NZ" },
                new Country{Id=150, Name="Nicaragua", Row = 150, ShortName="NI" },
                new Country{Id=151, Name="Niger (the)", Row = 151, ShortName="NE" },
                new Country{Id=152, Name="Nigeria", Row = 152, ShortName="NG" },
                new Country{Id=153, Name="Niue", Row = 153, ShortName="NU" },
                new Country{Id=154, Name="Norfolk Island", Row = 154, ShortName="NF" },
                new Country{Id=155, Name="Northern Mariana Islands (the)", Row = 155, ShortName="MP" },
                new Country{Id=156, Name="Norway", Row = 156, ShortName="NO" },
                new Country{Id=157, Name="Oman", Row = 157, ShortName="OM" },
                new Country{Id=158, Name="Pakistan", Row = 158, ShortName="PK" },
                new Country{Id=159, Name="Palau", Row = 159, ShortName="PW" },
                new Country{Id=160, Name="Palestine, State of", Row = 160, ShortName="PS" },
                new Country{Id=161, Name="Panama", Row = 161, ShortName="PA" },
                new Country{Id=162, Name="Papua New Guinea", Row = 162, ShortName="PG" },
                new Country{Id=163, Name="Paraguay", Row = 163, ShortName="PY" },
                new Country{Id=164, Name="Peru", Row = 164, ShortName="PE" },
                new Country{Id=165, Name="Philippines (the)", Row = 165, ShortName="PH" },
                new Country{Id=166, Name="Pitcairn", Row = 166, ShortName="PN" },
                new Country{Id=167, Name="Poland", Row = 167, ShortName="PL" },
                new Country{Id=168, Name="Portugal", Row = 168, ShortName="PT" },
                new Country{Id=169, Name="Puerto Rico", Row = 169, ShortName="PR" },
                new Country{Id=170, Name="Qatar", Row = 170, ShortName="QA" },
                new Country{Id=171, Name="Republic of North Macedonia", Row = 171, ShortName="MK" },
                new Country{Id=172, Name="Romania", Row = 172, ShortName="RO" },
                new Country{Id=173, Name="Russian Federation (the)", Row = 173, ShortName="RU" },
                new Country{Id=174, Name="Rwanda", Row = 174, ShortName="RW" },
                new Country{Id=175, Name="Réunion", Row = 175, ShortName="RE" },
                new Country{Id=176, Name="Saint Barthélemy", Row = 176, ShortName="BL" },
                new Country{Id=177, Name="Saint Helena, Ascension and Tristan da Cunha", Row = 177, ShortName="SH" },
                new Country{Id=178, Name="Saint Kitts and Nevis", Row = 178, ShortName="KN" },
                new Country{Id=179, Name="Saint Lucia", Row = 179, ShortName="LC" },
                new Country{Id=180, Name="Saint Martin (French part)", Row = 180, ShortName="MF" },
                new Country{Id=181, Name="Saint Pierre and Miquelon", Row = 181, ShortName="PM" },
                new Country{Id=182, Name="Saint Vincent and the Grenadines", Row = 182, ShortName="VC" },
                new Country{Id=183, Name="Samoa", Row = 183, ShortName="WS" },
                new Country{Id=184, Name="San Marino", Row = 184, ShortName="SM" },
                new Country{Id=185, Name="Sao Tome and Principe", Row = 185, ShortName="ST" },
                new Country{Id=186, Name="Saudi Arabia", Row = 186, ShortName="SA" },
                new Country{Id=187, Name="Senegal", Row = 187, ShortName="SN" },
                new Country{Id=188, Name="Serbia", Row = 188, ShortName="RS" },
                new Country{Id=189, Name="Seychelles", Row = 189, ShortName="SC" },
                new Country{Id=190, Name="Sierra Leone", Row = 190, ShortName="SL" },
                new Country{Id=191, Name="Singapore", Row = 191, ShortName="SG" },
                new Country{Id=192, Name="Sint Maarten (Dutch part)", Row = 192, ShortName="SX" },
                new Country{Id=193, Name="Slovakia", Row = 193, ShortName="SK" },
                new Country{Id=194, Name="Slovenia", Row = 194, ShortName="SI" },
                new Country{Id=195, Name="Solomon Islands", Row = 195, ShortName="SB" },
                new Country{Id=196, Name="Somalia", Row = 196, ShortName="SO" },
                new Country{Id=197, Name="South Africa", Row = 197, ShortName="ZA" },
                new Country{Id=198, Name="South Georgia and the South Sandwich Islands", Row = 198, ShortName="GS" },
                new Country{Id=199, Name="South Sudan", Row = 199, ShortName="SS" },
                new Country{Id=200, Name="Spain", Row = 200, ShortName="ES" },
                new Country{Id=201, Name="Sri Lanka", Row = 201, ShortName="LK" },
                new Country{Id=202, Name="Sudan (the)", Row = 202, ShortName="SD" },
                new Country{Id=203, Name="Suriname", Row = 203, ShortName="SR" },
                new Country{Id=204, Name="Svalbard and Jan Mayen", Row = 204, ShortName="SJ" },
                new Country{Id=205, Name="Sweden", Row = 205, ShortName="SE" },
                new Country{Id=206, Name="Switzerland", Row = 206, ShortName="CH" },
                new Country{Id=207, Name="Syrian Arab Republic", Row = 207, ShortName="SY" },
                new Country{Id=208, Name="Taiwan (Province of China)", Row = 208, ShortName="TW" },
                new Country{Id=209, Name="Tajikistan", Row = 209, ShortName="TJ" },
                new Country{Id=210, Name="Tanzania, United Republic of", Row = 210, ShortName="TZ" },
                new Country{Id=211, Name="Thailand", Row = 211, ShortName="TH" },
                new Country{Id=212, Name="Timor-Leste", Row = 212, ShortName="TL" },
                new Country{Id=213, Name="Togo", Row = 213, ShortName="TG" },
                new Country{Id=214, Name="Tokelau", Row = 214, ShortName="TK" },
                new Country{Id=215, Name="Tonga", Row = 215, ShortName="TO" },
                new Country{Id=216, Name="Trinidad and Tobago", Row = 216, ShortName="TT" },
                new Country{Id=217, Name="Tunisia", Row = 217, ShortName="TN" },
                new Country{Id=218, Name="Turkey", Row = 218, ShortName="TR" },
                new Country{Id=219, Name="Turkmenistan", Row = 219, ShortName="TM" },
                new Country{Id=220, Name="Turks and Caicos Islands (the)", Row = 220, ShortName="TC" },
                new Country{Id=221, Name="Tuvalu", Row = 221, ShortName="TV" },
                new Country{Id=222, Name="Uganda", Row = 222, ShortName="UG" },
                new Country{Id=223, Name="Ukraine", Row = 223, ShortName="UA" },
                new Country{Id=224, Name="United Arab Emirates (the)", Row = 224, ShortName="AE" },
                new Country{Id=225, Name="United Kingdom of Great Britain and Northern Ireland (the)", Row = 225, ShortName="GB" },
                new Country{Id=226, Name="United States Minor Outlying Islands (the)", Row = 226, ShortName="UM" },
                new Country{Id=227, Name="United States of America (the)", Row = 227, ShortName="US" },
                new Country{Id=228, Name="Uruguay", Row = 228, ShortName="UY" },
                new Country{Id=229, Name="Uzbekistan", Row = 229, ShortName="UZ" },
                new Country{Id=230, Name="Vanuatu", Row = 230, ShortName="VU" },
                new Country{Id=231, Name="Venezuela (Bolivarian Republic of)", Row = 231, ShortName="VE" },
                new Country{Id=232, Name="Viet Nam", Row = 232, ShortName="VN" },
                new Country{Id=233, Name="Virgin Islands (British)", Row = 233, ShortName="VG" },
                new Country{Id=234, Name="Virgin Islands (U.S.)", Row = 234, ShortName="VI" },
                new Country{Id=235, Name="Wallis and Futuna", Row = 235, ShortName="WF" },
                new Country{Id=236, Name="Western Sahara", Row = 236, ShortName="EH" },
                new Country{Id=237, Name="Yemen", Row = 237, ShortName="YE" },
                new Country{Id=238, Name="Zambia", Row = 238, ShortName="ZM" },
                new Country{Id=239, Name="Zimbabwe", Row = 239, ShortName="ZW" },
                new Country{Id=240, Name="Åland Islands", Row = 240, ShortName="AX" },
                new Country{Id=241, Name="Iceland", Row = 241, ShortName="IS" },
                new Country{Id=242, Name="India", Row = 242, ShortName="IN" },
                new Country{Id=243, Name="Indonesia", Row = 243, ShortName="ID" },
                new Country{Id=244, Name="Iran (Islamic Republic of)", Row = 244, ShortName="IR" },
                new Country{Id=245, Name="Iraq", Row = 245, ShortName="IQ" },
                new Country{Id=246, Name="Ireland", Row = 246, ShortName="IE" },
                new Country{Id=247, Name="Isle of Man", Row = 247, ShortName="IM" },
                new Country{Id=248, Name="Israel", Row = 248, ShortName="IL" },
                new Country{Id=249, Name="Italy", Row = 249, ShortName="IT" }
            };

            modelBuilder.Entity<Country>().HasData(countries);
        }
    }
}
